export interface Question {
  id: number;
  gradeGroup: 'preschool' | 'grade1' | 'grade2' | 'grade3' | 'grade4' | 'grade5';
  difficulty: 'easy' | 'medium' | 'hard';
  question: string;
  options: string[];
  correct: number;
  obstacleType: string;
}

export interface LeaderboardEntry {
  name: string;
  score: number;
  gradeLabel: string;
  difficultyLabel: string;
  date: string;
}

export const ALL_QUESTIONS: Question[] = [
  // ==========================================
  // 🧸 MẦM NON (50 CÂU HỎI)
  // ==========================================
  { id: 1, gradeGroup: 'preschool', difficulty: 'easy', question: 'Con vật nào sủa "Gâu gâu"?', options: ['Con mèo', 'Con gà', 'Con chó', 'Con vịt'], correct: 2, obstacleType: '🧱 Tường gạch' },
  { id: 2, gradeGroup: 'preschool', difficulty: 'easy', question: 'Hình nào có 3 cạnh?', options: ['Hình vuông', 'Hình tròn', 'Hình tam giác', 'Hình chữ nhật'], correct: 2, obstacleType: '🌊 Vũng nước' },
  { id: 3, gradeGroup: 'preschool', difficulty: 'easy', question: 'Quả nào có màu đỏ khi chín?', options: ['Quả chuối', 'Quả cà chua', 'Quả dưa chuột', 'Quả ổi xanh'], correct: 1, obstacleType: '🚧 Hàng rào' },
  { id: 4, gradeGroup: 'preschool', difficulty: 'easy', question: 'Bộ phận nào dùng để nghe âm thanh?', options: ['Mắt', 'Tai', 'Mũi', 'Miệng'], correct: 1, obstacleType: '⚡ Bẫy điện nhỏ' },
  { id: 5, gradeGroup: 'preschool', difficulty: 'easy', question: 'Con cá bơi ở đâu?', options: ['Trên cạn', 'Dưới nước', 'Trên cây', 'Trong không trung'], correct: 1, obstacleType: '🪵 Khúc gỗ' },
  { id: 6, gradeGroup: 'preschool', difficulty: 'easy', question: 'Mặt trời mọc ở hướng nào?', options: ['Hướng Đông', 'Hướng Tây', 'Hướng Nam', 'Hướng Bắc'], correct: 0, obstacleType: '🔥 Lửa nhỏ' },
  { id: 7, gradeGroup: 'preschool', difficulty: 'easy', question: 'Cái ô (dù) dùng để làm gì?', options: ['Che mưa che nắng', 'Để đi chân', 'Để ăn uống', 'Để mặc'], correct: 0, obstacleType: '🧱 Tường gạch' },
  { id: 8, gradeGroup: 'preschool', difficulty: 'easy', question: 'Con gà kêu như thế nào?', options: ['Ò v ó o', 'Meo meo', 'Gâu gâu', 'Ú oà'], correct: 0, obstacleType: '🌊 Vũng nước' },
  { id: 9, gradeGroup: 'preschool', difficulty: 'easy', question: 'Màu nào là màu của lá cây bình thường?', options: ['Màu đỏ', 'Màu xanh lá', 'Màu hồng', 'Màu cam'], correct: 1, obstacleType: '🚧 Hàng rào' },
  { id: 10, gradeGroup: 'preschool', difficulty: 'easy', question: 'Con mèo thích ăn gì nhất?', options: ['Cá', 'Cỏ', 'Xương', 'Đá'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 11, gradeGroup: 'preschool', difficulty: 'medium', question: '2 + 1 bằng mấy?', options: ['2', '3', '4', '5'], correct: 1, obstacleType: '🚧 Hàng rào' },
  { id: 12, gradeGroup: 'preschool', difficulty: 'medium', question: 'Có 2 quả táo, mẹ cho thêm 2 quả nữa, hỏi có mấy quả?', options: ['3 quả', '4 quả', '5 quả', '6 quả'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 13, gradeGroup: 'preschool', difficulty: 'medium', question: 'Con vật nào leo trèo rất giỏi trên cây?', options: ['Con cá', 'Con khỉ', 'Con vịt', 'Con bò'], correct: 1, obstacleType: '🪵 Khúc gỗ' },
  { id: 14, gradeGroup: 'preschool', difficulty: 'medium', question: 'Lá cây thường có màu gì?', options: ['Màu đỏ', 'Màu xanh lá', 'Màu đen', 'Màu tím'], correct: 1, obstacleType: '🔥 Lửa nhỏ' },
  { id: 15, gradeGroup: 'preschool', difficulty: 'medium', question: 'Đâu là phương tiện giao thông đường thủy?', options: ['Xe đạp', 'Máy bay', 'Tàu thủy', 'Ô tô'], correct: 2, obstacleType: '🧱 Tường gạch' },
  { id: 16, gradeGroup: 'preschool', difficulty: 'medium', question: 'Mùa nào thời tiết rất lạnh và có tuyết (ở xứ lạnh)?', options: ['Mùa hè', 'Mùa đông', 'Mùa thu', 'Mùa xuân'], correct: 1, obstacleType: '🌊 Vũng nước' },
  { id: 17, gradeGroup: 'preschool', difficulty: 'medium', question: 'Bàn tay chúng ta có tất cả bao nhiêu ngón tay?', options: ['8 ngón', '10 ngón', '12 ngón', '5 ngón'], correct: 1, obstacleType: '🚧 Hàng rào' },
  { id: 18, gradeGroup: 'preschool', difficulty: 'medium', question: 'Con gì gáy báo thức vào buổi sáng?', options: ['Con vịt', 'Con gà trống', 'Con lợn', 'Con trâu'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 19, gradeGroup: 'preschool', difficulty: 'medium', question: 'Bộ phận nào giúp chúng ta ngửi mùi hương?', options: ['Mắt', 'Tai', 'Mũi', 'Miệng'], correct: 2, obstacleType: '🪵 Khúc gỗ' },
  { id: 20, gradeGroup: 'preschool', difficulty: 'medium', question: 'Nước sôi có tính chất gì?', options: ['Rất lạnh', 'Rất nóng', 'Ngọt', 'Chua'], correct: 1, obstacleType: '🔥 Lửa nhỏ' },
  { id: 21, gradeGroup: 'preschool', difficulty: 'hard', question: 'Số nào lớn nhất trong các số sau?', options: ['3', '5', '2', '4'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 22, gradeGroup: 'preschool', difficulty: 'hard', question: 'Hình nào có 4 cạnh bằng nhau?', options: ['Hình tròn', 'Hình vuông', 'Hình tam giác', 'Hình chữ nhật'], correct: 1, obstacleType: '🪵 Khúc gỗ' },
  { id: 23, gradeGroup: 'preschool', difficulty: 'hard', question: 'Con gì cổ rất dài và ăn lá cây trên cao?', options: ['Con thỏ', 'Con hươu cao cổ', 'Con mèo', 'Con chuột'], correct: 1, obstacleType: '🔥 Lửa thần' },
  { id: 24, gradeGroup: 'preschool', difficulty: 'hard', question: 'Số liền sau số 4 là số mấy?', options: ['3', '5', '6', '2'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 25, gradeGroup: 'preschool', difficulty: 'hard', question: 'Cái gì giúp chúng ta nhìn thấy mọi vật?', options: ['Tai', 'Mũi', 'Mắt', 'Miệng'], correct: 2, obstacleType: '🧱 Tường lửa' },
  { id: 26, gradeGroup: 'preschool', difficulty: 'hard', question: '3 quả táo bớt đi 1 quả còn mấy quả?', options: ['1 quả', '2 quả', '3 quả', '0 quả'], correct: 1, obstacleType: '🌊 Vũng sâu' },
  { id: 27, gradeGroup: 'preschool', difficulty: 'hard', question: 'Con vật nào kêu "Meo meo"?', options: ['Con chó', 'Con mèo', 'Con vịt', 'Con lợn'], correct: 1, obstacleType: '🚧 Hàng rào gai' },
  { id: 28, gradeGroup: 'preschool', difficulty: 'hard', question: 'Đâu là loài hoa nở vào mùa xuân?', options: ['Hoa đào/Hoa mai', 'Hoa súng', 'Hoa sen', 'Hoa cúc vàng'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 29, gradeGroup: 'preschool', difficulty: 'hard', question: 'Trước khi ăn cơm chúng ta phải làm gì?', options: ['Rửa tay sạch sẽ', 'Đi ngủ ngay', 'Chạy nhảy', 'Xem TV'], correct: 0, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 30, gradeGroup: 'preschool', difficulty: 'hard', question: 'Cầu vồng có bao nhiêu màu sắc chính?', options: ['5 màu', '7 màu', '10 màu', '3 màu'], correct: 1, obstacleType: '🔥 Lửa thần' },
  { id: 31, gradeGroup: 'preschool', difficulty: 'hard', question: 'Trái đất quay quanh cái gì?', options: ['Mặt trơi', 'Mặt trời', 'Ngôi sao khác', 'Mặt trăng'], correct: 1, obstacleType: '🧱 Tường lửa' },
  { id: 32, gradeGroup: 'preschool', difficulty: 'hard', question: 'Đâu là bộ phận trên khuôn mặt?', options: ['Bàn chân', 'Cái mũi', 'Đầu gối', 'Khuỷu tay'], correct: 1, obstacleType: '🌊 Vũng sâu' },
  { id: 33, gradeGroup: 'preschool', difficulty: 'hard', question: 'Con thỏ thích ăn củ gì nhất?', options: ['Củ khoai tây', 'Củ cà rốt', 'Củ su hào', 'Củ hành'], correct: 1, obstacleType: '🚧 Hàng rào gai' },
  { id: 34, gradeGroup: 'preschool', difficulty: 'hard', question: 'Khi trời mưa, chúng ta thường dùng gì để không bị ướt?', options: ['Áo mưa hoặc ô', 'Quạt máy', 'Kính râm', 'Mũ len'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 35, gradeGroup: 'preschool', difficulty: 'hard', question: 'Con voi có đặc điểm gì nổi bật?', options: ['Có cái vòi dài', 'Biết bay', 'Nhỏ như con kiến', 'Có vảy cá'], correct: 0, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 36, gradeGroup: 'preschool', difficulty: 'hard', question: 'Đâu là con vật sống dưới nước?', options: ['Con hổ', 'Con cá mập', 'Con ngựa', 'Con gà'], correct: 1, obstacleType: '🔥 Lửa thần' },
  { id: 37, gradeGroup: 'preschool', difficulty: 'hard', question: 'Một năm có mấy mùa ở miền Bắc Việt Nam?', options: ['2 mùa', '3 mùa', '4 mùa', '5 mùa'], correct: 2, obstacleType: '🧱 Tường lửa' },
  { id: 38, gradeGroup: 'preschool', difficulty: 'hard', question: 'Con gì đẻ trứng và kêu cục tác?', options: ['Con chó', 'Con gà mái', 'Con mèo', 'Con cừu'], correct: 1, obstacleType: '🌊 Vũng sâu' },
  { id: 39, gradeGroup: 'preschool', difficulty: 'hard', question: 'Màu của máu chúng ta là màu gì?', options: ['Màu xanh', 'Màu đỏ', 'Màu vàng', 'Màu đen'], correct: 1, obstacleType: '🚧 Hàng rào gai' },
  { id: 40, gradeGroup: 'preschool', difficulty: 'hard', question: 'Bộ phận nào giúp chúng ta di chuyển, đi lại?', options: ['Đôi chân', 'Đôi tay', 'Cái đầu', 'Đôi tai'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 41, gradeGroup: 'preschool', difficulty: 'hard', question: 'Cây cối cần gì để lớn lên và xanh tốt?', options: ['Nước và ánh sáng', 'Bóng tối', 'Đá sỏi', 'Nhựa đường'], correct: 0, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 42, gradeGroup: 'preschool', difficulty: 'hard', question: 'Đâu là dụng cụ để viết chữ?', options: ['Cái kéo', 'Bút chì', 'Cái thìa', 'Cái bát'], correct: 1, obstacleType: '🔥 Lửa thần' },
  { id: 43, gradeGroup: 'preschool', difficulty: 'hard', question: 'Mặt trăng thường xuất hiện vào thời gian nào?', options: ['Ban ngày', 'Ban đêm', 'Buổi trưa', 'Lúc sáng sớm'], correct: 1, obstacleType: '🧱 Tường lửa' },
  { id: 44, gradeGroup: 'preschool', difficulty: 'hard', question: 'Con gì có cánh, biết bay và hút mật hoa?', options: ['Con ong', 'Con trâu', 'Con mèo', 'Con chuột'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 45, gradeGroup: 'preschool', difficulty: 'hard', question: 'Đâu là con vật hung dữ sống trong rừng sâu?', options: ['Con hổ (cọp)', 'Con thỏ', 'Con mèo nhà', 'Con gà tây'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 46, gradeGroup: 'preschool', difficulty: 'hard', question: 'Khi ngủ chúng ta nằm ở đâu?', options: ['Trên giường', 'Trên ngọn cây', 'Dưới lòng đường', 'Trong vũng nước'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 47, gradeGroup: 'preschool', difficulty: 'hard', question: 'Mũi dùng để làm gì?', options: ['Ngửi và thở', 'Để nghe', 'Để nhìn', 'Để nhai'], correct: 0, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 48, gradeGroup: 'preschool', difficulty: 'hard', question: 'Bánh chưng thường được ăn vào dịp nào ở Việt Nam?', options: ['Tết Nguyên Đán', 'Trung thu', 'Halloween', 'Giáng sinh'], correct: 0, obstacleType: '🔥 Lửa thần' },
  { id: 49, gradeGroup: 'preschool', difficulty: 'hard', question: 'Đâu là phương tiện giao thông đường bộ?', options: ['Xe máy', 'Tàu thủy', 'Máy bay', 'Tàu ngầm'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 50, gradeGroup: 'preschool', difficulty: 'hard', question: 'Màu kết hợp giữa màu xanh dương và màu vàng là màu gì?', options: ['Màu xanh lá', 'Màu đỏ', 'Màu hồng', 'Màu tím'], correct: 0, obstacleType: '🌊 Vũng sâu' },

  // ==========================================
  // 🎒 LỚP 1 (50 CÂU HỎI)
  // ==========================================
  { id: 51, gradeGroup: 'grade1', difficulty: 'easy', question: 'Kết quả của: 5 + 3 = ?', options: ['7', '8', '9', '6'], correct: 1, obstacleType: '🧱 Tường chắn' },
  { id: 52, gradeGroup: 'grade1', difficulty: 'easy', question: 'Số 7 đọc là gì?', options: ['Sáu', 'Bảy', 'Tám', 'Chín'], correct: 1, obstacleType: '🌊 Vũng nước' },
  { id: 53, gradeGroup: 'grade1', difficulty: 'easy', question: '4 cộng 4 bằng mấy?', options: ['6', '7', '8', '9'], correct: 2, obstacleType: '🚧 Hàng rào' },
  { id: 54, gradeGroup: 'grade1', difficulty: 'easy', question: 'Số nào lớn hơn số 5?', options: ['3', '4', '6', '2'], correct: 2, obstacleType: '⚡ Bẫy điện' },
  { id: 55, gradeGroup: 'grade1', difficulty: 'easy', question: '10 trừ 5 bằng mấy?', options: ['3', '4', '5', '6'], correct: 2, obstacleType: '🪵 Khúc gỗ' },
  { id: 56, gradeGroup: 'grade1', difficulty: 'easy', question: 'Số liền trước của số 2 là số mấy?', options: ['0', '1', '3', '4'], correct: 1, obstacleType: '🔥 Lửa nhỏ' },
  { id: 57, gradeGroup: 'grade1', difficulty: 'easy', question: 'Hình vuông có mấy góc vuông?', options: ['2 góc', '3 góc', '4 góc', 'Không có'], correct: 2, obstacleType: '🧱 Tường gạch' },
  { id: 58, gradeGroup: 'grade1', difficulty: 'easy', question: '6 + 2 bằng mấy?', options: ['7', '8', '9', '10'], correct: 1, obstacleType: '🌊 Vũng nước' },
  { id: 59, gradeGroup: 'grade1', difficulty: 'easy', question: 'Số nào nhỏ hơn số 3?', options: ['4', '1', '5', '6'], correct: 1, obstacleType: '🚧 Hàng rào' },
  { id: 60, gradeGroup: 'grade1', difficulty: 'easy', question: '2 cộng 2 bằng mấy?', options: ['3', '4', '5', '6'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 61, gradeGroup: 'grade1', difficulty: 'medium', question: 'Số liền trước của số 10 là số mấy?', options: ['8', '9', '11', '10'], correct: 1, obstacleType: '🚧 Hàng rào' },
  { id: 62, gradeGroup: 'grade1', difficulty: 'medium', question: 'Kết quả phép tính: 9 - 3 = ?', options: ['5', '6', '7', '8'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 63, gradeGroup: 'grade1', difficulty: 'medium', question: 'Số nào bé nhất trong các số: 4, 9, 2, 7?', options: ['9', '7', '4', '2'], correct: 3, obstacleType: '🪵 Khúc gỗ' },
  { id: 64, gradeGroup: 'grade1', difficulty: 'medium', question: 'Điền số thích hợp: 3 + ... = 7', options: ['3', '4', '5', '2'], correct: 1, obstacleType: '🔥 Lửa nhỏ' },
  { id: 65, gradeGroup: 'grade1', difficulty: 'medium', question: 'Số liền sau của số 18 là gì?', options: ['17', '19', '20', '18'], correct: 1, obstacleType: '🧱 Tường gạch' },
  { id: 66, gradeGroup: 'grade1', difficulty: 'medium', question: 'Hôm nay thứ Hai, ngày mai là thứ mấy?', options: ['Thứ Chủ Nhật', 'Thứ Ba', 'Thứ Tư', 'Thứ Bảy'], correct: 1, obstacleType: '🌊 Vũng nước' },
  { id: 67, gradeGroup: 'grade1', difficulty: 'medium', question: 'Trong các số 12, 15, 11, 19, số lớn nhất là?', options: ['12', '15', '11', '19'], correct: 3, obstacleType: '🚧 Hàng rào' },
  { id: 68, gradeGroup: 'grade1', difficulty: 'medium', question: 'Kết quả của: 7 - 4 = ?', options: ['2', '3', '4', '5'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 69, gradeGroup: 'grade1', difficulty: 'medium', question: 'Số gồm 1 chục và 5 đơn vị là số mấy?', options: ['51', '15', '105', '55'], correct: 1, obstacleType: '🪵 Khúc gỗ' },
  { id: 70, gradeGroup: 'grade1', difficulty: 'medium', question: 'Điền dấu thích hợp: 8 ... 5 + 2', options: ['>', '<', '=', 'Không xác định'], correct: 0, obstacleType: '🔥 Lửa nhỏ' },
  { id: 71, gradeGroup: 'grade1', difficulty: 'hard', question: '10 trừ đi 4 bằng mấy?', options: ['5', '7', '6', '8'], correct: 2, obstacleType: '⚡ Bẫy điện' },
  { id: 72, gradeGroup: 'grade1', difficulty: 'hard', question: 'Tính: 6 + 4 - 3 = ?', options: ['6', '7', '8', '5'], correct: 1, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 73, gradeGroup: 'grade1', difficulty: 'hard', question: 'Mẹ mua 12 cái kẹo, ăn hết 4 cái, hỏi còn lại mấy cái?', options: ['6 cái', '7 cái', '8 cái', '9 cái'], correct: 2, obstacleType: '🔥 Lửa thần' },
  { id: 74, gradeGroup: 'grade1', difficulty: 'hard', question: 'Số có hai chữ số giống nhau và lớn nhất là số mấy?', options: ['90', '99', '88', '77'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 75, gradeGroup: 'grade1', difficulty: 'hard', question: 'Điền dấu thích hợp: 15 ... 10 + 5', options: ['>', '<', '=', 'Không xác định'], correct: 2, obstacleType: '🧱 Tường lửa' },
  { id: 76, gradeGroup: 'grade1', difficulty: 'hard', question: 'Lan có 8 quyển vở, Nam cho thêm 5 quyển. Lan có tất cả bao nhiêu quyển?', options: ['12 quyển', '13 quyển', '14 quyển', '15 quyển'], correct: 1, obstacleType: '🌊 Vũng sâu' },
  { id: 77, gradeGroup: 'grade1', difficulty: 'hard', question: 'Kết quả của: 20 - 10 + 5 = ?', options: ['10', '15', '20', '25'], correct: 1, obstacleType: '🚧 Hàng rào gai' },
  { id: 78, gradeGroup: 'grade1', difficulty: 'hard', question: 'Số gồm 1 chục và 4 đơn vị là số mấy?', options: ['41', '14', '104', '44'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 79, gradeGroup: 'grade1', difficulty: 'hard', question: 'Đồng hồ chỉ 12 giờ đúng, kim phút và kim giờ chỉ vào số nào?', options: ['Cùng chỉ số 6', 'Cùng chỉ số 12', 'Chỉ số 3 và 9', 'Chỉ số 1 và 2'], correct: 1, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 80, gradeGroup: 'grade1', difficulty: 'hard', question: 'Có 16 học sinh ở sân chơi, thêm 4 học sinh đi ra. Hỏi có tất cả bao nhiêu học sinh?', options: ['18', '20', '22', '12'], correct: 1, obstacleType: '🔥 Lửa thần' },
  { id: 81, gradeGroup: 'grade1', difficulty: 'hard', question: 'Số lớn nhất có một chữ số là:', options: ['8', '9', '10', '7'], correct: 1, obstacleType: '🧱 Tường lửa' },
  { id: 82, gradeGroup: 'grade1', difficulty: 'hard', question: 'Số bé nhất có hai chữ số là:', options: ['10', '11', '09', '20'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 83, gradeGroup: 'grade1', difficulty: 'hard', question: 'Kết quả phép tính: 14 + 3 - 5 = ?', options: ['10', '11', '12', '9'], correct: 2, obstacleType: '🚧 Hàng rào gai' },
  { id: 84, gradeGroup: 'grade1', difficulty: 'hard', question: 'Hôm nay là thứ Ba, ngày hôm qua là thứ mấy?', options: ['Thứ Tư', 'Thứ Hai', 'Thứ Năm', 'Chủ Nhật'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 85, gradeGroup: 'grade1', difficulty: 'hard', question: 'Nhà An có 5 con gà, mẹ mua thêm 4 con gà nữa. Hỏi nhà An có mấy con gà?', options: ['8 con', '9 con', '10 con', '7 con'], correct: 1, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 86, gradeGroup: 'grade1', difficulty: 'hard', question: 'Tính: 19 - 9 + 4 = ?', options: ['12', '14', '15', '13'], correct: 1, obstacleType: '🔥 Lửa thần' },
  { id: 87, gradeGroup: 'grade1', difficulty: 'hard', question: 'Số nào lớn hơn 12 và nhỏ hơn 14?', options: ['11', '13', '15', '10'], correct: 1, obstacleType: '🧱 Tường lửa' },
  { id: 88, gradeGroup: 'grade1', difficulty: 'hard', question: 'Đâu là hình tròn trong các hình học cơ bản?', options: ['Hình bánh xe', 'Hình chiếc khăn vuông', 'Hình cuốn vở', 'Hình lá cờ'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 89, gradeGroup: 'grade1', difficulty: 'hard', question: 'Bình có 10 viên bi, Bình cho Nam 3 viên. Bình còn lại mấy viên bi?', options: ['6 viên', '7 viên', '8 viên', '5 viên'], correct: 1, obstacleType: '🚧 Hàng rào gai' },
  { id: 90, gradeGroup: 'grade1', difficulty: 'hard', question: 'Số liền sau của số 9 là số mấy?', options: ['8', '10', '11', '12'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 91, gradeGroup: 'grade1', difficulty: 'hard', question: 'Tính: 5 + 5 + 5 = ?', options: ['10', '15', '20', '12'], correct: 1, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 92, gradeGroup: 'grade1', difficulty: 'hard', question: 'Sắp xếp các số sau theo thứ tự từ bé đến lớn: 5, 2, 8, 1:', options: ['8, 5, 2, 1', '1, 2, 5, 8', '2, 1, 5, 8', '1, 5, 2, 8'], correct: 1, obstacleType: '🔥 Lửa thần' },
  { id: 93, gradeGroup: 'grade1', difficulty: 'hard', question: 'Tổ 1 có 6 bạn, tổ 2 có 5 bạn. Cả hai tổ có bao nhiêu bạn?', options: ['10 bạn', '11 bạn', '12 bạn', '9 bạn'], correct: 1, obstacleType: '🧱 Tường lửa' },
  { id: 94, gradeGroup: 'grade1', difficulty: 'hard', question: '1 chục bằng bao nhiêu đơn vị?', options: ['5 đơn vị', '10 đơn vị', '100 đơn vị', '50 đơn vị'], correct: 1, obstacleType: '🌊 Vũng sâu' },
  { id: 95, gradeGroup: 'grade1', difficulty: 'hard', question: 'Kết quả của: 18 - 8 = ?', options: ['8', '10', '12', '0'], correct: 1, obstacleType: '🚧 Hàng rào gai' },
  { id: 96, gradeGroup: 'grade1', difficulty: 'hard', question: 'Điền số thích hợp: 10 + ... = 16', options: ['5', '6', '7', '8'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 97, gradeGroup: 'grade1', difficulty: 'hard', question: 'Độ dài đoạn thẳng AB bằng 7cm, đoạn thẳng CD bằng 5cm. Đoạn thẳng nào dài hơn?', options: ['Đoạn AB', 'Đoạn CD', 'Hai đoạn bằng nhau', 'Không xác định'], correct: 0, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 98, gradeGroup: 'grade1', difficulty: 'hard', question: 'Mẹ hái được 11 bông hoa, bố hái được 8 bông hoa. Cả hai người hái được bao nhiêu bông hoa?', options: ['18 bông', '19 bông', '20 bông', '17 bông'], correct: 1, obstacleType: '🔥 Lửa thần' },
  { id: 99, gradeGroup: 'grade1', difficulty: 'hard', question: 'Số nào ở giữa số 14 và số 16?', options: ['13', '15', '17', '12'], correct: 1, obstacleType: '🧱 Tường lửa' },
  { id: 100, gradeGroup: 'grade1', difficulty: 'hard', question: 'Kết quả của: 20 - 5 - 5 = ?', options: ['5', '10', '15', '0'], correct: 1, obstacleType: '🌊 Vũng sâu' },

  // ==========================================
  // 📚 LỚP 2 (50 CÂU HỎI)
  // ==========================================
  { id: 101, gradeGroup: 'grade2', difficulty: 'easy', question: 'Kết quả: 15 + 27 = ?', options: ['40', '42', '45', '52'], correct: 1, obstacleType: '🌊 Dòng nước lũ' },
  { id: 102, gradeGroup: 'grade2', difficulty: 'easy', question: '3 x 4 bằng mấy?', options: ['10', '12', '14', '16'], correct: 1, obstacleType: '🧱 Tường chắn' },
  { id: 103, gradeGroup: 'grade2', difficulty: 'easy', question: '1 tuần lễ có mấy ngày?', options: ['5 ngày', '6 ngày', '7 ngày', '8 ngày'], correct: 2, obstacleType: '🚧 Hàng rào' },
  { id: 104, gradeGroup: 'grade2', difficulty: 'easy', question: 'Kết quả: 50 - 18 = ?', options: ['32', '38', '42', '22'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 105, gradeGroup: 'grade2', difficulty: 'easy', question: 'Đâu là kết quả của phép tính 20 : 2?', options: ['5', '8', '10', '12'], correct: 2, obstacleType: '🪵 Khúc gỗ' },
  { id: 106, gradeGroup: 'grade2', difficulty: 'easy', question: '1 mét bằng bao nhiêu đề-xi-mét?', options: ['10 dm', '100 dm', '1 dm', '1000 dm'], correct: 0, obstacleType: '🔥 Lửa nhỏ' },
  { id: 107, gradeGroup: 'grade2', difficulty: 'easy', question: 'Số liền sau của 99 là?', options: ['98', '100', '101', '90'], correct: 1, obstacleType: '🧱 Tường gạch' },
  { id: 108, gradeGroup: 'grade2', difficulty: 'easy', question: '4 x 5 bằng bao nhiêu?', options: ['15', '20', '25', '30'], correct: 1, obstacleType: '🌊 Vũng nước' },
  { id: 109, gradeGroup: 'grade2', difficulty: 'easy', question: '2 x 8 bằng mấy?', options: ['14', '16', '18', '12'], correct: 1, obstacleType: '🚧 Hàng rào' },
  { id: 110, gradeGroup: 'grade2', difficulty: 'easy', question: '10 : 2 bằng mấy?', options: ['3', '4', '5', '6'], correct: 2, obstacleType: '⚡ Bẫy điện' },
  { id: 111, gradeGroup: 'grade2', difficulty: 'medium', question: 'Kết quả phép nhân: 2 x 5 = ?', options: ['7', '12', '10', '15'], correct: 2, obstacleType: '🚧 Hàng rào gai' },
  { id: 112, gradeGroup: 'grade2', difficulty: 'medium', question: 'Tìm x biết: x + 12 = 35', options: ['13', '23', '47', '25'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 113, gradeGroup: 'grade2', difficulty: 'medium', question: '1 năm có bao nhiêu tháng?', options: ['10 tháng', '11 tháng', '12 tháng', '24 tháng'], correct: 2, obstacleType: '🪵 Khúc gỗ' },
  { id: 114, gradeGroup: 'grade2', difficulty: 'medium', question: 'Kết quả của: 18 : 3 + 15 = ?', options: ['21', '20', '19', '25'], correct: 0, obstacleType: '🔥 Lửa nhỏ' },
  { id: 115, gradeGroup: 'grade2', difficulty: 'medium', question: 'Số gồm 4 trăm, 5 chục và 3 đơn vị viết là?', options: ['345', '543', '453', '435'], correct: 2, obstacleType: '🧱 Tường gạch' },
  { id: 116, gradeGroup: 'grade2', difficulty: 'medium', question: 'Chu vi hình tam giác có các cạnh 3cm, 4cm, 5cm là?', options: ['10cm', '12cm', '15cm', '60cm'], correct: 1, obstacleType: '🌊 Vũng nước' },
  { id: 117, gradeGroup: 'grade2', difficulty: 'medium', question: '5 x 7 = ?', options: ['30', '35', '40', '45'], correct: 1, obstacleType: '🚧 Hàng rào' },
  { id: 118, gradeGroup: 'grade2', difficulty: 'medium', question: 'Tìm x biết: 15 - x = 7', options: ['6', '7', '8', '9'], correct: 2, obstacleType: '⚡ Bẫy điện' },
  { id: 119, gradeGroup: 'grade2', difficulty: 'medium', question: '3 kg + 15 kg - 8 kg = ?', options: ['9 kg', '10 kg', '11 kg', '12 kg'], correct: 1, obstacleType: '🪵 Khúc gỗ' },
  { id: 120, gradeGroup: 'grade2', difficulty: 'medium', question: 'Số lớn nhất có hai chữ số là:', options: ['90', '99', '10', '100'], correct: 1, obstacleType: '🔥 Lửa nhỏ' },
  { id: 121, gradeGroup: 'grade2', difficulty: 'hard', question: 'Tìm x biết: x - 15 = 35', options: ['20', '40', '50', '60'], correct: 2, obstacleType: '⚡ Bẫy điện' },
  { id: 122, gradeGroup: 'grade2', difficulty: 'hard', question: 'Lớp 2A có 32 học sinh, lớp 2B có nhiều hơn lớp 2A 4 học sinh. Hỏi lớp 2B có bao nhiêu học sinh?', options: ['28 học sinh', '36 học sinh', '34 học sinh', '30 học sinh'], correct: 1, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 123, gradeGroup: 'grade2', difficulty: 'hard', question: 'Tính nhanh: 2 x 3 x 4 = ?', options: ['20', '24', '18', '12'], correct: 1, obstacleType: '🔥 Lửa thần' },
  { id: 124, gradeGroup: 'grade2', difficulty: 'hard', question: 'Hiện nay con 8 tuổi, mẹ 32 tuổi. Hỏi mẹ hơn con bao nhiêu tuổi?', options: ['20 tuổi', '24 tuổi', '22 tuổi', '26 tuổi'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 125, gradeGroup: 'grade2', difficulty: 'hard', question: 'Thùng thứ nhất có 45 lít dầu, thùng thứ hai có ít hơn thùng thứ nhất 15 lít. Hỏi thùng thứ hai có bao nhiêu lít dầu?', options: ['30 lít', '60 lít', '25 lít', '35 lít'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 126, gradeGroup: 'grade2', difficulty: 'hard', question: 'Kết quả của biểu thức: 50 - 5 x 6 = ?', options: ['270', '20', '40', '25'], correct: 1, obstacleType: '🌊 Vũng sâu' },
  { id: 127, gradeGroup: 'grade2', difficulty: 'hard', question: 'Mỗi hộp có 6 cái bánh. Hỏi 5 hộp như thế có bao nhiêu cái bánh?', options: ['24 cái', '30 cái', '36 cái', '11 cái'], correct: 1, obstacleType: '🚧 Hàng rào gai' },
  { id: 128, gradeGroup: 'grade2', difficulty: 'hard', question: 'Số lớn nhất có 3 chữ số khác nhau là:', options: ['999', '987', '978', '989'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 129, gradeGroup: 'grade2', difficulty: 'hard', question: 'Tìm x biết: x x 3 = 27', options: ['7', '8', '9', '6'], correct: 2, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 130, gradeGroup: 'grade2', difficulty: 'hard', question: 'Một sợi dây dài 40cm, cắt đi 1/4 độ dài sợi dây. Hỏi đoạn dây còn lại dài bao nhiêu?', options: ['10cm', '20cm', '30cm', '15cm'], correct: 2, obstacleType: '🔥 Lửa thần' },
  { id: 131, gradeGroup: 'grade2', difficulty: 'hard', question: 'Số liền trước của số 100 là:', options: ['99', '101', '90', '98'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 132, gradeGroup: 'grade2', difficulty: 'hard', question: 'Độ dài đường gấp khúc gồm 3 đoạn thẳng lần lượt là 4cm, 5cm, 6cm là:', options: ['14 cm', '15 cm', '16 cm', '13 cm'], correct: 1, obstacleType: '🌊 Vũng sâu' },
  { id: 133, gradeGroup: 'grade2', difficulty: 'hard', question: 'Kết quả của phép tính: 36 : 4 + 14 = ?', options: ['23', '24', '22', '25'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 134, gradeGroup: 'grade2', difficulty: 'hard', question: 'Mẹ mua 24 quả cam, biếu ông bà một nửa số cam đó. Hỏi mẹ còn lại bao nhiêu quả cam?', options: ['10 quả', '12 quả', '14 quả', '8 quả'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 135, gradeGroup: 'grade2', difficulty: 'hard', question: 'Năm nay Nam 8 tuổi, anh Hải 14 tuổi. Hỏi 3 năm nữa anh Hải hơn Nam mấy tuổi?', options: ['6 tuổi', '9 tuổi', '5 tuổi', '7 tuổi'], correct: 0, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 136, gradeGroup: 'grade2', difficulty: 'hard', question: 'Tính: 5 x 8 - 15 = ?', options: ['25', '30', '40', '20'], correct: 0, obstacleType: '🔥 Lửa thần' },
  { id: 137, gradeGroup: 'grade2', difficulty: 'hard', question: 'Tìm x biết: 48 - x = 24', options: ['22', '24', '26', '20'], correct: 1, obstacleType: '🧱 Tường lửa' },
  { id: 138, gradeGroup: 'grade2', difficulty: 'hard', question: 'Một cửa hàng buổi sáng bán được 34kg đường, buổi chiều bán được nhiều hơn buổi sáng 12kg đường. Hỏi buổi chiều bán được bao nhiêu kg đường?', options: ['42 kg', '46 kg', '48 kg', '44 kg'], correct: 1, obstacleType: '🌊 Vũng sâu' },
  { id: 139, gradeGroup: 'grade2', difficulty: 'hard', question: 'Kết quả của biểu thức: 100 - (15 + 25) = ?', options: ['50', '60', '70', '40'], correct: 1, obstacleType: '🚧 Hàng rào gai' },
  { id: 140, gradeGroup: 'grade2', difficulty: 'hard', question: 'Số nhỏ nhất có 3 chữ số là:', options: ['000', '100', '101', '110'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 141, gradeGroup: 'grade2', difficulty: 'hard', question: '3dm 5cm đổi ra cm là:', options: ['35 cm', '53 cm', '305 cm', '8 cm'], correct: 0, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 142, gradeGroup: 'grade2', difficulty: 'hard', question: 'Cho dãy số: 2, 4, 6, 8, ... Số hạng tiếp theo của dãy số là:', options: ['9', '10', '12', '11'], correct: 1, obstacleType: '🔥 Lửa thần' },
  { id: 143, gradeGroup: 'grade2', difficulty: 'hard', question: 'Có 30 học sinh xếp thành các hàng, mỗi hàng có 5 học sinh. Hỏi có tất cả bao nhiêu hàng?', options: ['5 hàng', '6 hàng', '7 hàng', '8 hàng'], correct: 1, obstacleType: '🧱 Tường lửa' },
  { id: 144, gradeGroup: 'grade2', difficulty: 'hard', question: 'Tính: 27 : 3 + 12 = ?', options: ['20', '21', '22', '19'], correct: 1, obstacleType: '🌊 Vũng sâu' },
  { id: 145, gradeGroup: 'grade2', difficulty: 'hard', question: 'Một hình vuông có cạnh dài 6cm. Chu vi hình vuông đó là:', options: ['12 cm', '24 cm', '36 cm', '18 cm'], correct: 1, obstacleType: '🚧 Hàng rào gai' },
  { id: 146, gradeGroup: 'grade2', difficulty: 'hard', question: 'Tìm x biết: x : 5 = 7', options: ['30', '35', '40', '25'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 147, gradeGroup: 'grade2', difficulty: 'hard', question: 'Mẹ hái 42 quả cam, bà hái 28 quả cam. Cả hai người hái được bao nhiêu quả cam?', options: ['60 quả', '70 quả', '80 quả', '68 quả'], correct: 1, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 148, gradeGroup: 'grade2', difficulty: 'hard', question: 'Một tuần Nam đi học 5 ngày. Hỏi trong 4 tuần Nam đi học bao nhiêu ngày?', options: ['15 ngày', '20 ngày', '25 ngày', '30 ngày'], correct: 1, obstacleType: '🔥 Lửa thần' },
  { id: 149, gradeGroup: 'grade2', difficulty: 'hard', question: 'Kết quả của: 1 giờ chiều cùng ngày còn gọi là mấy giờ?', options: ['11 giờ', '12 giờ', '13 giờ', '14 giờ'], correct: 2, obstacleType: '🧱 Tường lửa' },
  { id: 150, gradeGroup: 'grade2', difficulty: 'hard', question: 'Số gồm 7 trăm, 0 chục, 5 đơn vị viết là:', options: ['750', '705', '507', '570'], correct: 1, obstacleType: '🌊 Vũng sâu' },

  // ==========================================
  // ✏️ LỚP 3 (50 CÂU HỎI)
  // ==========================================
  { id: 151, gradeGroup: 'grade3', difficulty: 'easy', question: 'Kết quả phép nhân: 7 x 8 = ?', options: ['54', '56', '64', '49'], correct: 1, obstacleType: '🧱 Tường lửa' },
  { id: 152, gradeGroup: 'grade3', difficulty: 'easy', question: '54 : 6 bằng mấy?', options: ['7', '8', '9', '6'], correct: 2, obstacleType: '🌊 Vũng nước' },
  { id: 153, gradeGroup: 'grade3', difficulty: 'easy', question: 'Chu vi hình vuông cạnh 5cm là?', options: ['15cm', '20cm', '25cm', '10cm'], correct: 1, obstacleType: '🚧 Hàng rào' },
  { id: 154, gradeGroup: 'grade3', difficulty: 'easy', question: '9 x 9 bằng bao nhiêu?', options: ['72', '81', '79', '90'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 155, gradeGroup: 'grade3', difficulty: 'easy', question: '1kg bằng bao nhiêu gam?', options: ['10g', '100g', '1000g', '500g'], correct: 2, obstacleType: '🪵 Khúc gỗ' },
  { id: 156, gradeGroup: 'grade3', difficulty: 'easy', question: 'Số liền trước của 1000 là?', options: ['998', '999', '900', '99'], correct: 1, obstacleType: '🔥 Lửa nhỏ' },
  { id: 157, gradeGroup: 'grade3', difficulty: 'easy', question: '6 x 7 = ?', options: ['36', '42', '48', '56'], correct: 1, obstacleType: '🧱 Tường gạch' },
  { id: 158, gradeGroup: 'grade3', difficulty: 'easy', question: '48 : 8 = ?', options: ['5', '6', '7', '8'], correct: 1, obstacleType: '🌊 Vũng nước' },
  { id: 159, gradeGroup: 'grade3', difficulty: 'easy', question: '8 x 4 = ?', options: ['24', '32', '36', '28'], correct: 1, obstacleType: '🚧 Hàng rào' },
  { id: 160, gradeGroup: 'grade3', difficulty: 'easy', question: '72 : 9 = ?', options: ['7', '8', '9', '6'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 161, gradeGroup: 'grade3', difficulty: 'medium', question: '1 giờ có bao nhiêu phút?', options: ['30 phút', '50 phút', '60 phút', '100 phút'], correct: 2, obstacleType: '🌊 Vũng sâu' },
  { id: 162, gradeGroup: 'grade3', difficulty: 'medium', question: 'Tìm x biết: x : 4 = 8', options: ['24', '32', '28', '36'], correct: 1, obstacleType: '🚧 Hàng rào gai' },
  { id: 163, gradeGroup: 'grade3', difficulty: 'medium', question: 'Diện tích hình chữ nhật có chiều dài 6cm, rộng 4cm là?', options: ['20 cm²', '24 cm²', '10 cm²', '12 cm²'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 164, gradeGroup: 'grade3', difficulty: 'medium', question: 'Số dư trong phép chia 29 : 5 là:', options: ['1', '2', '3', '4'], correct: 3, obstacleType: '🪵 Khúc gỗ' },
  { id: 165, gradeGroup: 'grade3', difficulty: 'medium', question: 'Tháng nào trong năm có ít ngày nhất?', options: ['Tháng 1', 'Tháng 2', 'Tháng 4', 'Tháng 12'], correct: 1, obstacleType: '🔥 Lửa nhỏ' },
  { id: 166, gradeGroup: 'grade3', difficulty: 'medium', question: 'Góc vuông là góc có số đo bằng bao nhiêu?', options: ['45 độ', '90 độ', '180 độ', '60 độ'], correct: 1, obstacleType: '🧱 Tường gạch' },
  { id: 167, gradeGroup: 'grade3', difficulty: 'medium', question: 'Kết quả của biểu thức: 125 + 25 x 3 = ?', options: ['450', '200', '175', '300'], correct: 1, obstacleType: '🌊 Vũng nước' },
  { id: 168, gradeGroup: 'grade3', difficulty: 'medium', question: 'Tìm x biết: x x 6 = 54', options: ['7', '8', '9', '6'], correct: 2, obstacleType: '🚧 Hàng rào' },
  { id: 169, gradeGroup: 'grade3', difficulty: 'medium', question: 'Một ngày có bao nhiêu giờ?', options: ['12 giờ', '24 giờ', '48 giờ', '36 giờ'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 170, gradeGroup: 'grade3', difficulty: 'medium', question: 'Tính chu vi hình chữ nhật có chiều dài 10cm, chiều rộng 6cm:', options: ['32 cm', '16 cm', '60 cm', '30 cm'], correct: 0, obstacleType: '🪵 Khúc gỗ' },
  { id: 171, gradeGroup: 'grade3', difficulty: 'hard', question: 'Tính: 72 : 8 = ?', options: ['7', '8', '9', '6'], correct: 2, obstacleType: '⚡ Bẫy điện' },
  { id: 172, gradeGroup: 'grade3', difficulty: 'hard', question: 'Một cửa hàng có 360kg gạo, đã bán đi 1/3 số gạo đó. Hỏi cửa hàng còn lại bao nhiêu kg gạo?', options: ['120kg', '240kg', '180kg', '200kg'], correct: 1, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 173, gradeGroup: 'grade3', difficulty: 'hard', question: 'Năm 2024 là thế kỷ mấy?', options: ['Thế kỷ 19', 'Thế kỷ 20', 'Thế kỷ 21', 'Thế kỷ 22'], correct: 2, obstacleType: '🔥 Lửa thần' },
  { id: 174, gradeGroup: 'grade3', difficulty: 'hard', question: 'Tìm x biết: (x + 15) x 2 = 60', options: ['15', '20', '25', '30'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 175, gradeGroup: 'grade3', difficulty: 'hard', question: 'Một mảnh vườn hình chữ nhật có chiều dài 12m, chiều rộng bằng 1/3 chiều dài. Tính chu vi mảnh vườn đó?', options: ['32m', '16m', '48m', '24m'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 176, gradeGroup: 'grade3', difficulty: 'hard', question: 'Có 4 thùng đựng dầu, mỗi thùng chứa 45 lít. Nếu lấy ra 50 lít thì còn lại bao nhiêu lít dầu?', options: ['130 lít', '120 lít', '140 lít', '110 lít'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 177, gradeGroup: 'grade3', difficulty: 'hard', question: 'Giá trị của biểu thức: 1000 - 200 x 3 + 50 là:', options: ['450', '350', '650', '550'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 178, gradeGroup: 'grade3', difficulty: 'hard', question: 'Một sợi dây dài 36cm được uốn thành một hình vuông. Hỏi cạnh hình vuông dài bao nhiêu?', options: ['6cm', '9cm', '12cm', '4cm'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 179, gradeGroup: 'grade3', difficulty: 'hard', question: 'Mẹ sinh con năm mẹ 24 tuổi. Hỏi khi con 12 tuổi thì mẹ bao nhiêu tuổi?', options: ['34 tuổi', '36 tuổi', '38 tuổi', '40 tuổi'], correct: 1, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 180, gradeGroup: 'grade3', difficulty: 'hard', question: 'Số dư lớn nhất của phép chia cho 7 là:', options: ['5', '6', '7', '8'], correct: 1, obstacleType: '🔥 Lửa thần' },
  { id: 181, gradeGroup: 'grade3', difficulty: 'hard', question: 'Một hình chữ nhật có chiều rộng 7cm, chiều dài gấp 3 lần chiều rộng. Diện tích hình chữ nhật đó là:', options: ['147 cm²', '49 cm²', '21 cm²', '98 cm²'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 182, gradeGroup: 'grade3', difficulty: 'hard', question: 'Tìm x biết: 84 : x = 4', options: ['21', '19', '22', '20'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 183, gradeGroup: 'grade3', difficulty: 'hard', question: 'Một cửa hàng có 450m vải, đã bán đi 1/5 số mét vải đó. Hỏi cửa hàng còn lại bao nhiêu mét vải?', options: ['360 m', '90 m', '350 m', '400 m'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 184, gradeGroup: 'grade3', difficulty: 'hard', question: 'Cho biểu thức: A = 45 + 15 x 3. Giá trị của biểu thức A là:', options: ['180', '90', '120', '150'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 185, gradeGroup: 'grade3', difficulty: 'hard', question: 'An có 42 viên bi, Bình có số bi bằng 1/6 số bi của An. Cả hai bạn có bao nhiêu viên bi?', options: ['49 viên', '50 viên', '48 viên', '52 viên'], correct: 0, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 186, gradeGroup: 'grade3', difficulty: 'hard', question: 'Tính giá trị: 560g + 240g - 150g = ?', options: ['650 g', '750 g', '800 g', '700 g'], correct: 0, obstacleType: '🔥 Lửa thần' },
  { id: 187, gradeGroup: 'grade3', difficulty: 'hard', question: 'Tìm số có 3 chữ số, biết chữ số hàng trăm là số lớn nhất có 1 chữ số, hàng chục bằng 1/3 hàng trăm, hàng đơn vị kém hàng chục 2 đơn vị.', options: ['931', '932', '933', '930'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 188, gradeGroup: 'grade3', difficulty: 'hard', question: 'Một hình vuông có chu vi là 48cm. Diện tích của hình vuông đó là:', options: ['144 cm²', '192 cm²', '96 cm²', '12 cm²'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 189, gradeGroup: 'grade3', difficulty: 'hard', question: 'Thùng thứ nhất chứa 36 lít dầu, gấp 4 lần số lít dầu ở thùng thứ hai. Cả hai thùng chứa bao nhiêu lít dầu?', options: ['45 lít', '54 lít', '48 lít', '40 lít'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 190, gradeGroup: 'grade3', difficulty: 'hard', question: 'Hôm nay là thứ Năm, ngày 12 tháng 5. Hỏi thứ Năm tuần sau là ngày bao nhiêu của tháng 5?', options: ['ngày 18', 'ngày 19', 'ngày 20', 'ngày 21'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 191, gradeGroup: 'grade3', difficulty: 'hard', question: 'Giá trị của biểu thức: (45 + 25) : 5 là:', options: ['12', '14', '16', '18'], correct: 1, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 192, gradeGroup: 'grade3', difficulty: 'hard', question: 'Một mảnh vườn hình chữ nhật có chu vi 80m, chiều rộng 15m. Chiều dài mảnh vườn là:', options: ['25 m', '30 m', '35 m', '40 m'], correct: 0, obstacleType: '🔥 Lửa thần' },
  { id: 193, gradeGroup: 'grade3', difficulty: 'hard', question: 'Tìm x biết: x x 7 + 15 = 63', options: ['6', '7', '8', '9'], correct: 1, obstacleType: '🧱 Tường lửa' },
  { id: 194, gradeGroup: 'grade3', difficulty: 'hard', question: 'Có 56 học sinh chia đều thành các nhóm, mỗi nhóm có 7 học sinh. Hỏi chia được bao nhiêu nhóm?', options: ['7 nhóm', '8 nhóm', '9 nhóm', '6 nhóm'], correct: 1, obstacleType: '🌊 Vũng sâu' },
  { id: 195, gradeGroup: 'grade3', difficulty: 'hard', question: 'Đổi 2 phút 15 giây ra giây ta được:', options: ['135 giây', '125 giây', '145 giây', '150 giây'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 196, gradeGroup: 'grade3', difficulty: 'hard', question: 'Một người mang 72 quả trứng ra chợ bán, đã bán được 3/8 số trứng đó. Hỏi người đó còn lại bao nhiêu quả trứng?', options: ['45 quả', '27 quả', '54 quả', '36 quả'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 197, gradeGroup: 'grade3', difficulty: 'hard', question: 'Số liền sau của số lớn nhất có 3 chữ số là:', options: ['999', '1000', '1001', '998'], correct: 1, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 198, gradeGroup: 'grade3', difficulty: 'hard', question: 'Kết quả của: 846 - 235 + 112 = ?', options: ['723', '713', '733', '743'], correct: 0, obstacleType: '🔥 Lửa thần' },
  { id: 199, gradeGroup: 'grade3', difficulty: 'hard', question: 'Một quầy hàng có 84m vải xanh, số vải trắng bằng một nửa số vải xanh. Hỏi quầy hàng có bao nhiêu mét vải trắng?', options: ['42 m', '48 m', '36 m', '40 m'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 200, gradeGroup: 'grade3', difficulty: 'hard', question: 'Tính chu vi hình tam giác có các cạnh đều dài 15cm:', options: ['30 cm', '45 cm', '60 cm', '75 cm'], correct: 1, obstacleType: '🌊 Vũng sâu' },

  // ==========================================
  // 📐 LỚP 4 (50 CÂU HỎI)
  // ==========================================
  { id: 201, gradeGroup: 'grade4', difficulty: 'easy', question: 'Số nào chia hết cho cả 2, 3 và 5?', options: ['15', '30', '25', '12'], correct: 1, obstacleType: '⚡ Bẫy điện cao thế' },
  { id: 202, gradeGroup: 'grade4', difficulty: 'easy', question: 'Kết quả của phép tính: 125 x 4 = ?', options: ['400', '500', '600', '450'], correct: 1, obstacleType: '🧱 Tường chắn' },
  { id: 203, gradeGroup: 'grade4', difficulty: 'easy', question: 'Phân số nào bằng phân số 1/2?', options: ['2/3', '3/6', '4/5', '5/8'], correct: 1, obstacleType: '🌊 Vũng nước' },
  { id: 204, gradeGroup: 'grade4', difficulty: 'easy', question: '1 tấn bằng bao nhiêu kg?', options: ['100kg', '1000kg', '10kg', '10000kg'], correct: 1, obstacleType: '🚧 Hàng rào' },
  { id: 205, gradeGroup: 'grade4', difficulty: 'easy', question: 'Góc tù là góc có số đo như thế nào?', options: ['Nhỏ hơn góc vuông', 'Lớn hơn góc vuông và nhỏ hơn góc bẹt', 'Bằng góc vuông', 'Bằng 180 độ'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 206, gradeGroup: 'grade4', difficulty: 'easy', question: 'Kết quả của: 45000 : 9 = ?', options: ['5000', '500', '50000', '4000'], correct: 0, obstacleType: '🪵 Khúc gỗ' },
  { id: 207, gradeGroup: 'grade4', difficulty: 'easy', question: 'Trung bình cộng của 10, 20 và 30 là?', options: ['15', '20', '25', '30'], correct: 1, obstacleType: '🔥 Lửa nhỏ' },
  { id: 208, gradeGroup: 'grade4', difficulty: 'easy', question: 'Số chia hết cho 9 là số nào?', options: ['123', '456', '729', '341'], correct: 2, obstacleType: '🧱 Tường gạch' },
  { id: 209, gradeGroup: 'grade4', difficulty: 'easy', question: 'Số nào chia hết cho cả 2 và 5?', options: ['125', '230', '142', '315'], correct: 1, obstacleType: '🌊 Vũng nước' },
  { id: 210, gradeGroup: 'grade4', difficulty: 'easy', question: 'Kết quả của: 240 x 5 = ?', options: ['1000', '1200', '1100', '900'], correct: 1, obstacleType: '🚧 Hàng rào' },
  { id: 211, gradeGroup: 'grade4', difficulty: 'medium', question: 'Diện tích hình chữ nhật có chiều dài 8cm, rộng 5cm là?', options: ['40 cm²', '26 cm²', '13 cm²', '35 cm²'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 212, gradeGroup: 'grade4', difficulty: 'medium', question: 'Rút gọn phân số 8/12 ta được:', options: ['2/3', '3/4', '4/5', '1/2'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 213, gradeGroup: 'grade4', difficulty: 'medium', question: 'Kết quả của phép nhân 135 x 24 là gì?', options: ['3240', '3150', '2980', '3320'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 214, gradeGroup: 'grade4', difficulty: 'medium', question: 'Đâu là năm nhuận trong các năm sau?', options: ['2021', '2022', '2023', '2024'], correct: 3, obstacleType: '⚡ Bẫy điện' },
  { id: 215, gradeGroup: 'grade4', difficulty: 'medium', question: 'Tính giá trị biểu thức: 3/4 + 1/4 = ?', options: ['4/8', '1', '3/8', '4/0'], correct: 1, obstacleType: '🪵 Khúc gỗ' },
  { id: 216, gradeGroup: 'grade4', difficulty: 'medium', question: 'Số thích hợp điền vào chỗ chấm để 5m² 12dm² = ... dm² là:', options: ['512', '5012', '5120', '50012'], correct: 1, obstacleType: '🔥 Lửa nhỏ' },
  { id: 217, gradeGroup: 'grade4', difficulty: 'medium', question: 'Hiệu của hai số là 150, tỉ số của hai số là 3/5. Số lớn là:', options: ['375', '225', '300', '400'], correct: 0, obstacleType: '🧱 Tường gạch' },
  { id: 218, gradeGroup: 'grade4', difficulty: 'medium', question: 'Kết quả của phép tính: 5/6 - 1/3 = ?', options: ['1/2', '4/3', '2/3', '3/6'], correct: 0, obstacleType: '🌊 Vũng nước' },
  { id: 219, gradeGroup: 'grade4', difficulty: 'medium', question: 'Trung bình cộng của hai số là 45, biết số thứ nhất là 38. Số thứ hai là:', options: ['52', '48', '50', '46'], correct: 0, obstacleType: '🚧 Hàng rào' },
  { id: 220, gradeGroup: 'grade4', difficulty: 'medium', question: 'Kết quả của: 124 x 15 = ?', options: ['1860', '1750', '1920', '1680'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 221, gradeGroup: 'grade4', difficulty: 'hard', question: '1/4 thế kỷ bằng bao nhiêu năm?', options: ['20 năm', '25 năm', '50 năm', '75 năm'], correct: 1, obstacleType: '🌋 Hố dung nham' },
  { id: 222, gradeGroup: 'grade4', difficulty: 'hard', question: 'Tổng của hai số là 100, hiệu của hai số là 20. Tìm số lớn?', options: ['40', '50', '60', '70'], correct: 2, obstacleType: '⚡ Bẫy điện cao thế' },
  { id: 223, gradeGroup: 'grade4', difficulty: 'hard', question: 'Một khu đất hình chữ nhật có chu vi 160m, chiều rộng bằng 3/5 chiều dài. Diện tích khu đất là:', options: ['1500 m²', '1350 m²', '1440 m²', '1600 m²'], correct: 0, obstacleType: '🌋 Hố dung nham' },
  { id: 224, gradeGroup: 'grade4', difficulty: 'hard', question: 'Tìm x biết: 3/4 : x = 9/8', options: ['2/3', '3/2', '1/2', '4/3'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 225, gradeGroup: 'grade4', difficulty: 'hard', question: 'Trung bình cộng tuổi của bố, mẹ và An là 28 tuổi. Biết bố 40 tuổi, mẹ 36 tuổi. Hỏi An bao nhiêu tuổi?', options: ['8 tuổi', '10 tuổi', '12 tuổi', '14 tuổi'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 226, gradeGroup: 'grade4', difficulty: 'hard', question: 'Mua 3 quyển vở hết 24000 đồng. Hỏi mua 8 quyển vở như thế hết bao nhiêu tiền?', options: ['64000 đồng', '56000 đồng', '72000 đồng', '48000 đồng'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 227, gradeGroup: 'grade4', difficulty: 'hard', question: 'Kết quả của phép tính: (1 - 1/2) x (1 - 1/3) x (1 - 1/4) = ?', options: ['1/4', '1/2', '3/4', '1/3'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 228, gradeGroup: 'grade4', difficulty: 'hard', question: 'Một hình bình hành có độ dài đáy là 24cm, chiều cao bằng 1/3 độ dài đáy. Diện tích hình bình hành đó là:', options: ['192 cm²', '96 cm²', '288 cm²', '64 cm²'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 229, gradeGroup: 'grade4', difficulty: 'hard', question: 'Tìm chữ số x để số 7x5 chia hết cho 9:', options: ['x = 3', 'x = 6', 'x = 5', 'x = 9'], correct: 1, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 230, gradeGroup: 'grade4', difficulty: 'hard', question: 'Hàng ngày Nam đi học với vận tốc 4km/giờ và đi hết 30 phút. Quãng đường từ nhà Nam đến trường là:', options: ['2km', '4km', '1.5km', '3km'], correct: 0, obstacleType: '🔥 Lửa thần' },
  { id: 231, gradeGroup: 'grade4', difficulty: 'hard', question: 'Cho phân số 5/7. Nếu cộng thêm vào tử số và mẫu số cùng một số tự nhiên ta được phân số mới bằng 3/4. Số tự nhiên đó là:', options: ['1', '2', '3', '4'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 232, gradeGroup: 'grade4', difficulty: 'hard', question: 'Tổng của hai số là 2024, số lớn gấp 3 lần số bé. Số lớn là:', options: ['1518', '506', '1214', '1350'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 233, gradeGroup: 'grade4', difficulty: 'hard', question: 'Một hình chữ nhật có chu vi 120m, chiều dài hơn chiều rộng 16m. Diện tích hình chữ nhật đó là:', options: ['864 m²', '800 m²', '900 m²', '750 m²'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 234, gradeGroup: 'grade4', difficulty: 'hard', question: 'Tính bằng cách thuận tiện nhất: 25 x 13 x 4 = ?', options: ['1300', '1200', '1400', '1100'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 235, gradeGroup: 'grade4', difficulty: 'hard', question: 'Hiệu của hai số là 202, thương của hai số là 3. Số bé là:', options: ['101', '303', '202', '150'], correct: 0, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 236, gradeGroup: 'grade4', difficulty: 'hard', question: 'Đổi: 4 tấn 50kg = ... kg:', options: ['4050 kg', '4500 kg', '4005 kg', '450 kg'], correct: 0, obstacleType: '🔥 Lửa thần' },
  { id: 237, gradeGroup: 'grade4', difficulty: 'hard', question: 'Một mảnh vườn hình thoi có độ dài các đường chéo là 30m và 40m. Diện tích mảnh vườn là:', options: ['600 m²', '1200 m²', '700 m²', '500 m²'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 238, gradeGroup: 'grade4', difficulty: 'hard', question: 'Tìm x biết: x x 12 = 1440', options: ['120', '100', '110', '130'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 239, gradeGroup: 'grade4', difficulty: 'hard', question: 'Trung bình cộng của ba số là 75. Biết số thứ nhất bằng 60, số thứ hai bằng 80. Số thứ ba là:', options: ['85', '90', '75', '70'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 240, gradeGroup: 'grade4', difficulty: 'hard', question: 'Phân số lớn nhất trong các phân số sau: 3/4, 5/6, 7/12, 2/3 là:', options: ['5/6', '3/4', '7/12', '2/3'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 241, gradeGroup: 'grade4', difficulty: 'hard', question: 'Một đội công nhân làm đường trong 3 ngày đầu mỗi ngày làm được 240m, trong 2 ngày sau mỗi ngày làm được 340m. Trung bình mỗi ngày đội đó làm được bao nhiêu mét đường?', options: ['280 m', '290 m', '300 m', '270 m'], correct: 0, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 242, gradeGroup: 'grade4', difficulty: 'hard', question: 'Cho A = 3/4 + 5/8. Giá trị của A là:', options: ['11/8', '8/12', '15/32', '1'], correct: 0, obstacleType: '🔥 Lửa thần' },
  { id: 243, gradeGroup: 'grade4', difficulty: 'hard', question: 'Tìm số tự nhiên x biết rằng: 35 < x x 5 < 50 và x là số chẵn:', options: ['8', '10', '9', '6'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 244, gradeGroup: 'grade4', difficulty: 'hard', question: 'Một sân trường hình chữ nhật có chiều dài 60m, chiều rộng bằng 2/3 chiều dài. Chu vi sân trường đó là:', options: ['200 m', '100 m', '2400 m', '180 m'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 245, gradeGroup: 'grade4', difficulty: 'hard', question: 'Kết quả của phép tính: 48600 : 300 = ?', options: ['162', '1620', '16.2', '152'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 246, gradeGroup: 'grade4', difficulty: 'hard', question: 'Mẹ mua 5kg gạo tẻ và 3kg gạo nếp hết tổng cộng 135000 đồng. Giá 1kg gạo tẻ là 15000 đồng. Giá 1kg gạo nếp là:', options: ['20000 đồng', '18000 đồng', '25000 đồng', '22000 đồng'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 247, gradeGroup: 'grade4', difficulty: 'hard', question: 'Đổi: 3 giờ 15 phút = ... phút:', options: ['195 phút', '180 phút', '200 phút', '165 phút'], correct: 0, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 248, gradeGroup: 'grade4', difficulty: 'hard', question: 'Tìm x biết: 5/9 + x = 7/3', options: ['16/9', '2/9', '12/9', '14/9'], correct: 0, obstacleType: '🔥 Lửa thần' },
  { id: 249, gradeGroup: 'grade4', difficulty: 'hard', question: 'Một hình thoi có diện tích 240 cm², biết độ dài một đường chéo là 20cm. Độ dài đường chéo còn lại là:', options: ['24 cm', '12 cm', '48 cm', '30 cm'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 250, gradeGroup: 'grade4', difficulty: 'hard', question: 'Số dư của phép chia 4587 : 46 là:', options: ['31', '21', '41', '11'], correct: 0, obstacleType: '🌊 Vũng sâu' },

  // ==========================================
  // 🚀 LỚP 5 (50 CÂU HỎI)
  // ==========================================
  { id: 251, gradeGroup: 'grade5', difficulty: 'easy', question: 'Kết quả của biểu thức: 3/4 + 1/2 = ?', options: ['4/6', '5/4', '4/8', '2/3'], correct: 1, obstacleType: '🌋 Hố dung nham' },
  { id: 252, gradeGroup: 'grade5', difficulty: 'easy', question: 'Đổi ra số thập phân: 3/5 = ?', options: ['0.3', '0.5', '0.6', '0.8'], correct: 2, obstacleType: '🧱 Tường chắn' },
  { id: 253, gradeGroup: 'grade5', difficulty: 'easy', question: 'Diện tích hình thang có đáy lớn 12cm, đáy nhỏ 8cm, chiều cao 5cm là:', options: ['50 cm²', '100 cm²', '40 cm²', '60 cm²'], correct: 0, obstacleType: '🌊 Vũng nước' },
  { id: 254, gradeGroup: 'grade5', difficulty: 'easy', question: '25% của 200 là bao nhiêu?', options: ['25', '50', '75', '100'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 255, gradeGroup: 'grade5', difficulty: 'easy', question: 'Thể tích hình lập phương cạnh 3cm là?', options: ['9 cm³', '18 cm³', '27 cm³', '54 cm³'], correct: 2, obstacleType: '🔥 Lửa thần' },
  { id: 256, gradeGroup: 'grade5', difficulty: 'easy', question: 'Chu vi hình tròn có bán kính r = 5cm là (lấy pi = 3.14):', options: ['31.4 cm', '15.7 cm', '78.5 cm', '25 cm'], correct: 0, obstacleType: '🪵 Khúc gỗ' },
  { id: 257, gradeGroup: 'grade5', difficulty: 'easy', question: 'Kết quả của phép chia: 12.5 : 0.5 = ?', options: ['2.5', '25', '250', '0.25'], correct: 1, obstacleType: '🧱 Tường gạch' },
  { id: 258, gradeGroup: 'grade5', difficulty: 'easy', question: 'Hỗn số 2 và 3/4 viết dưới dạng phân số là:', options: ['9/4', '11/4', '8/4', '5/4'], correct: 1, obstacleType: '🌊 Vũng nước' },
  { id: 259, gradeGroup: 'grade5', difficulty: 'easy', question: 'Số thập phân gồm 5 đơn vị, 3 phần trăm viết là:', options: ['5.3', '5.03', '5.003', '5.30'], correct: 1, obstacleType: '🚧 Hàng rào' },
  { id: 260, gradeGroup: 'grade5', difficulty: 'easy', question: '10% của 450 là:', options: ['45', '4.5', '450', '4500'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 261, gradeGroup: 'grade5', difficulty: 'medium', question: 'Một ô tô đi với vận tốc 60 km/giờ trong 2 giờ 30 phút. Quãng đường ô tô đi được là:', options: ['120 km', '150 km', '130 km', '140 km'], correct: 1, obstacleType: '🚧 Hàng rào gai' },
  { id: 262, gradeGroup: 'grade5', difficulty: 'medium', question: 'Tìm x biết: x x 2.5 = 10', options: ['2', '4', '5', '2.5'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 263, gradeGroup: 'grade5', difficulty: 'medium', question: 'Diện tích toàn phần của hình lập phương có cạnh 4cm là:', options: ['96 cm²', '64 cm²', '48 cm²', '32 cm²'], correct: 0, obstacleType: '🪵 Khúc gỗ' },
  { id: 264, gradeGroup: 'grade5', difficulty: 'medium', question: 'Lớp học có 40 học sinh, trong đó có 24 học sinh nữ. Tỉ số phần trăm của số học sinh nữ và số học sinh cả lớp là:', options: ['50%', '60%', '40%', '70%'], correct: 1, obstacleType: '🔥 Lửa nhỏ' },
  { id: 265, gradeGroup: 'grade5', difficulty: 'medium', question: 'Kết quả của phép tính: 4 ngày 15 giờ + 2 ngày 10 giờ là:', options: ['6 ngày 25 giờ', '7 ngày 1 giờ', '7 ngày 5 giờ', '6 ngày 12 giờ'], correct: 1, obstacleType: '🧱 Tường gạch' },
  { id: 266, gradeGroup: 'grade5', difficulty: 'medium', question: 'Một bể cá hình hộp chữ nhật có chiều dài 80cm, rộng 40cm, cao 50cm. Thể tích bể cá là:', options: ['160 lít', '160000 cm³ (160 lít)', '1600 lít', '16 lít'], correct: 1, obstacleType: '🌊 Vũng nước' },
  { id: 267, gradeGroup: 'grade5', difficulty: 'medium', question: 'Số dư của phép chia 37.5 : 4 nếu lấy đến hai chữ số ở phần thập phân của thương là:', options: ['0.03', '0.3', '0.02', '0.2'], correct: 0, obstacleType: '🚧 Hàng rào' },
  { id: 268, gradeGroup: 'grade5', difficulty: 'medium', question: 'Tìm x biết: x : 1.5 = 4', options: ['5', '6', '4.5', '5.5'], correct: 1, obstacleType: '⚡ Bẫy điện' },
  { id: 269, gradeGroup: 'grade5', difficulty: 'medium', question: 'Diện tích xung quanh hình hộp chữ nhật có chiều dài 6dm, rộng 4dm, cao 5dm là:', options: ['100 dm²', '120 dm²', '80 dm²', '90 dm²'], correct: 0, obstacleType: '🪵 Khúc gỗ' },
  { id: 270, gradeGroup: 'grade5', difficulty: 'medium', question: 'Đổi ra mét khối: 4500 dm³ = ... m³:', options: ['4.5 m³', '45 m³', '0.45 m³', '450 m³'], correct: 0, obstacleType: '🔥 Lửa nhỏ' },
  { id: 271, gradeGroup: 'grade5', difficulty: 'hard', question: 'Mua 1kg đường phải trả 25000 đồng. Hỏi mua 3.5kg đường cùng loại phải trả bao nhiêu tiền?', options: ['75000 đồng', '87500 đồng', '80000 đồng', '90000 đồng'], correct: 1, obstacleType: '⚡ Bẫy điện cao thế' },
  { id: 272, gradeGroup: 'grade5', difficulty: 'hard', question: 'Một hình hộp chữ nhật có diện tích xung quanh là 420 cm², chiều cao 7cm. Nửa chu vi mặt đáy của hình hộp chữ nhật đó là:', options: ['30 cm', '60 cm', '15 cm', '45 cm'], correct: 0, obstacleType: '🌋 Hố dung nham' },
  { id: 273, gradeGroup: 'grade5', difficulty: 'hard', question: 'Lãi suất tiết kiệm là 0.6% một tháng. Người đó gửi 100 triệu đồng thì sau 1 tháng nhận được bao nhiêu tiền lãi?', options: ['600000 đồng', '60000 đồng', '6000000 đồng', '6000 đồng'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 274, gradeGroup: 'grade5', difficulty: 'hard', question: 'Một can đựng dầu nặng tổng cộng 38.5kg. Sau khi dùng hết 3/4 số dầu thì can và phần dầu còn lại nặng 12.5kg. Hỏi vỏ can nặng bao nhiêu kg?', options: ['2.5 kg', '3.5 kg', '4.5 kg', '5.0 kg'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 275, gradeGroup: 'grade5', difficulty: 'hard', question: 'Hai thành phố A và B cách nhau 135 km. Cùng một lúc, một xe máy đi từ A về B và một ô tô đi từ B về A, sau 1.5 giờ thì gặp nhau. Tổng vận tốc của xe máy và ô tô là:', options: ['90 km/giờ', '100 km/giờ', '80 km/giờ', '85 km/giờ'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 276, gradeGroup: 'grade5', difficulty: 'hard', question: 'Tìm x biết: (x - 1.5) : 0.5 + 2.5 = 10', options: ['5.25', '4.75', '6.25', '5.75'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 277, gradeGroup: 'grade5', difficulty: 'hard', question: 'Một mảnh vườn hình chữ nhật có chiều dài gấp đôi chiều rộng. Nếu giảm chiều dài đi 3m và tăng chiều rộng lên 3m thì diện tích tăng thêm 18 m². Diện tích ban đầu của mảnh vườn là:', options: ['144 m²', '160 m²', '128 m²', '108 m²'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 278, gradeGroup: 'grade5', difficulty: 'hard', question: 'Cho hình tròn có bán kính tăng lên 2 lần thì diện tích hình tròn đó tăng lên mấy lần?', options: ['2 lần', '4 lần', '8 lần', '6 lần'], correct: 1, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 279, gradeGroup: 'grade5', difficulty: 'hard', question: 'Một ca nô xuôi dòng một khúc sông từ A đến B hết 2 giờ và ngược dòng từ B về A hết 3 giờ. Biết vận tốc dòng nước là 3 km/giờ. Vận tốc của ca nô khi nước lặng là:', options: ['15 km/giờ', '12 km/giờ', '18 km/giờ', '20 km/giờ'], correct: 0, obstacleType: '🔥 Lửa thần' },
  { id: 280, gradeGroup: 'grade5', difficulty: 'hard', question: 'Tổng của ba số bằng 197.5. Biết số thứ nhất bằng 1.5 số thứ hai, và số thứ hai bằng số thứ ba. Số thứ nhất là:', options: ['67.5', '45', '75', '82.5'], correct: 0, obstacleType: '🌋 Hố dung nham' },
  { id: 281, gradeGroup: 'grade5', difficulty: 'hard', question: 'Một hình lập phương có diện tích toàn phần là 216 cm². Thể tích của hình lập phương đó là:', options: ['216 cm³', '125 cm³', '64 cm³', '512 cm³'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 282, gradeGroup: 'grade5', difficulty: 'hard', question: 'Tìm x biết: 3.5 x (x - 2.4) = 14', options: ['6.4', '5.4', '4.4', '7.4'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 283, gradeGroup: 'grade5', difficulty: 'hard', question: 'Một lớp học có 40 học sinh, số học sinh nam chiếm 60%. Số học sinh nữ của lớp đó là:', options: ['16 học sinh', '24 học sinh', '20 học sinh', '18 học sinh'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 284, gradeGroup: 'grade5', difficulty: 'hard', question: 'Lúc 7 giờ sáng, một người đi xe đạp từ A với vận tốc 12 km/giờ. Đến 10 giờ sáng, một ô tô đi từ A đuổi theo với vận tốc 48 km/giờ. Ô tô đuổi kịp xe đạp lúc mấy giờ?', options: ['11 giờ', '12 giờ', '11 giờ 30 phút', '12 giờ 30 phút'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 285, gradeGroup: 'grade5', difficulty: 'hard', question: 'Cho hình thang có diện tích 180 cm², chiều cao 10cm. Hiệu hai đáy là 6cm. Độ dài đáy lớn của hình thang là:', options: ['21 cm', '15 cm', '24 cm', '18 cm'], correct: 0, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 286, gradeGroup: 'grade5', difficulty: 'hard', question: 'Một người bỏ ra 2000000 đồng tiền vốn để mua hàng. Sau khi bán hết, người đó lãi 20% so với tiền vốn. Tổng số tiền thu về (cả vốn lẫn lãi) là:', options: ['2400000 đồng', '2200000 đồng', '2500000 đồng', '2300000 đồng'], correct: 0, obstacleType: '🔥 Lửa thần' },
  { id: 287, gradeGroup: 'grade5', difficulty: 'hard', question: 'Đổi: 2.25 giờ = ... phút:', options: ['135 phút', '125 phút', '140 phút', '150 phút'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 288, gradeGroup: 'grade5', difficulty: 'hard', question: 'Tìm số tự nhiên x lớn nhất sao cho: x < 15.68:', options: ['15', '16', '14', '15.6'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 289, gradeGroup: 'grade5', difficulty: 'hard', question: 'Một mảnh đất hình chữ nhật có chu vi 100m, chiều dài bằng 3/2 chiều rộng. Diện tích mảnh đất đó là:', options: ['600 m²', '400 m²', '500 m²', '625 m²'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 290, gradeGroup: 'grade5', difficulty: 'hard', question: 'Kết quả của phép tính: (1 - 1/2) x (1 - 1/3) x (1 - 1/4) x (1 - 1/5) = ?', options: ['1/5', '1/4', '2/5', '1/10'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 291, gradeGroup: 'grade5', difficulty: 'hard', question: 'Thể tích của một khối gỗ hình hộp chữ nhật có chiều dài 1.2m, chiều rộng 0.5m và chiều cao 0.4m là:', options: ['0.24 m³', '2.4 m³', '0.12 m³', '1.2 m³'], correct: 0, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 292, gradeGroup: 'grade5', difficulty: 'hard', question: 'Tìm x biết: 12.4 - x : 2.5 = 8.4', options: ['10', '8', '12', '9'], correct: 0, obstacleType: '🔥 Lửa thần' },
  { id: 293, gradeGroup: 'grade5', difficulty: 'hard', question: 'Một hình tròn có diện tích là 78.5 cm². Bán kính của hình tròn đó là (lấy pi = 3.14):', options: ['5 cm', '10 cm', '2.5 cm', '7.5 cm'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 294, gradeGroup: 'grade5', difficulty: 'hard', question: 'Một xe máy đi với vận tốc 40 km/giờ. Quãng đường xe máy đi được trong 1 giờ 45 phút là:', options: ['70 km', '75 km', '68 km', '80 km'], correct: 0, obstacleType: '🌊 Vũng sâu' },
  { id: 295, gradeGroup: 'grade5', difficulty: 'hard', question: 'Tổng của hai số thập phân bằng 35.6. Nếu dịch chuyển dấu phẩy của số bé sang phải một chữ số thì được số lớn. Số bé là:', options: ['3.24', '3.56', '4.25', '3.16'], correct: 0, obstacleType: '🚧 Hàng rào gai' },
  { id: 296, gradeGroup: 'grade5', difficulty: 'hard', question: 'Giá trị của biểu thức: 45.6 + 12.3 x 2 - 15.5 là:', options: ['54.9', '60.5', '52.4', '58.2'], correct: 0, obstacleType: '⚡ Bẫy điện' },
  { id: 297, gradeGroup: 'grade5', difficulty: 'hard', question: 'Một cái thùng tôn không nắp hình hộp chữ nhật có chiều dài 8dm, rộng 5dm, cao 4dm. Diện tích tôn dùng để làm thùng đó là:', options: ['160 dm²', '180 dm²', '200 dm²', '140 dm²'], correct: 0, obstacleType: '🪵 Khúc gỗ lớn' },
  { id: 298, gradeGroup: 'grade5', difficulty: 'hard', question: 'Tìm x biết: x + x : 0.5 + x : 0.25 = 21', options: ['3', '2', '4', '5'], correct: 0, obstacleType: '🔥 Lửa thần' },
  { id: 299, gradeGroup: 'grade5', difficulty: 'hard', question: 'Đổi: 3m³ 45dm³ = ... m³:', options: ['3.045 m³', '3.45 m³', '3.0045 m³', '3.405 m³'], correct: 0, obstacleType: '🧱 Tường lửa' },
  { id: 300, gradeGroup: 'grade5', difficulty: 'hard', question: 'Một người đi xe lửa từ ga A đến ga B hết 6 giờ. Vận tốc xe lửa là 45 km/giờ. Quãng đường từ ga A đến ga B là:', options: ['270 km', '250 km', '300 km', '280 km'], correct: 0, obstacleType: '🌊 Vũng sâu' }
];